name: test calculadora-basica-tdd
on:
  push:
  pull_request:
    branches: [ main, development, feature-code ]
jobs:
  tests:
      run-on: ubuntu-latest
      steps:
        -name: Checkout repository
        uses: actions/checkout@v4

        -name: Set up Node.js 20
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'

        -name: Install dependencies (lockfile)
        run: npm ci

        -name: Run tests
        run: npm test

